version: '3.8'

services:
  # Your Next.js Application
  leaf-petals-web:
    build: .
    container_name: leaf_petals_app
    ports:
      - "8081:3000"
    environment:
      # We changed localhost to the name of the DB service below
      - MONGODB_URI=mongodb://leaf-petals-db:27017/LeafPetals
      - NEXTAUTH_SECRET=my_super_secret_plant_shop_key_2026
      # Note: We keep this as localhost:3000 because this is how users/tests access the app from the outside
      - NEXTAUTH_URL=http://localhost:3000
      - NODE_ENV=production
    depends_on:
      - leaf-petals-db
    networks:
      - leaf_petals_network

  # Your MongoDB Database Server
  leaf-petals-db:
    image: mongo:latest
    container_name: leaf_petals_db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db 
    networks:
      - leaf_petals_network

volumes:
  mongo_data:

networks:
  leaf_petals_network:
    driver: bridge